version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=6
      - SE_NODE_MAX_SESSIONS=6
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: 2gb
      #volumes:
    #- ./downloads:/home/seluser/Downloads
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=6
      - SE_NODE_MAX_SESSIONS=6
  seleniumdockerproject_chrome:
    build: .
    container_name: searchmodulecontainer_chrome
    volumes:
      - E:\MAX\IT\UDEMY\Selenium_WebDriver_with_Docker_Jenkins_AWS\test-output:/usr/share/udemy/test-output
    environment:
      - BROWSER=CHROME
      - HUB_HOST=hub
      - MODULE=search-module.xml
    depends_on:
      #- firefox
      - chrome
  seleniumdockerproject_firefox:
    build: .
    container_name: searchmodulecontainer_firefox
    volumes:
      - E:\MAX\IT\UDEMY\Selenium_WebDriver_with_Docker_Jenkins_AWS\test-output2:/usr/share/udemy/test-output
    environment:
      - BROWSER=FIREFOX
      - HUB_HOST=hub
      - MODULE=search-module.xml
    depends_on:
      - firefox
      #- chrome
  bookflight_test:
    build: .
    container_name: bookflight_container
    volumes:
      - E:\MAX\IT\UDEMY\Selenium_WebDriver_with_Docker_Jenkins_AWS\test-output-bookFlight:/usr/share/udemy/test-output
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    depends_on:
      - firefox
      - chrome

# docker compose up
# docker compose up  -d --scale chrome=3 --scale firefox=3
# mvn clean package -DskipTests